services:
  postgres:
    image: postgres:15-alpine
    container_name: wrm-postgres
    environment:
      POSTGRES_DB: wrm_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2002
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: wrm-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wrm_db_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2002
    ports:
      - "8080:8080"

volumes:
  postgres_data: