spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wrm_db_dev
    username: postgres
    password: 2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    ma.nabil.wrm: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

wrm:
  scheduling:
    algorithms:
      - FIFO
      - PRIORITY
      - SJF
  max-capacity:
    default: 10